#ifndef LV_CONF_H
#define LV_CONF_H

#define LV_COLOR_DEPTH 16
#define LV_COLOR_16_SWAP 0
#define LV_USE_PERF_MONITOR 0
#define LV_USE_GPU 0
#define LV_DRAW_COMPLEX 1
#define LV_USE_LOG 0
#define LV_USE_FS 0
#define LV_USE_LARGE_COORD 0
#define LV_USE_CLIPBOARD 0
#define LV_USE_THEME_DEFAULT 1
#define LV_FONT_MONTSERRAT_14 1
#define LV_USE_BIDI 0
#define LV_USE_ARABIC_PERSIAN_CHARS 0
#define LV_USE_ASSERT_NULL 0
#define LV_USE_ASSERT_MALLOC 0
#define LV_USE_ASSERT_MEM_INTEGRITY 0
#define LV_USE_ASSERT_OBJ 0
#define LV_USE_ASSERT_STYLE 0
#define LV_USE_SNAPSHOT 0
#define LV_USE_DEMO_WIDGETS 0

#endif
